AT-2388: initial commit
madedotcom/pygyver pull request #127
Opened 2020-11-03 11:23 UTC by dteok

2020-11-05 09:33 UTC, charlielewis reviewed
It looks good, but I suggest that:
- you add a unit test for the method `update_table_description`
- rename the argument simply `description` instead of `table_description`
- also modify `create_partition_table()` to accept this argument
- also consider adding it to `initiate_table()`, `load_gs_sheet()` and `create_gs_table()`, i.e. all the methods that themselves call `create_table()`

2020-11-05 10:58 UTC, KarimZaoui requested changes

2020-11-05 10:58 UTC, KarimZaoui commented on pygyver/etl/dw.py
> +        table_ref = dataset_ref.table(table_id)
can be simplified to 

```suggestion
        table_ref = self.get_table_ref(dataset_id=dataset_id, table_id=table_id, project_id=project_id)
```

2020-11-05 10:58 UTC, KarimZaoui commented on tests/test_dw.py
> +        )
This does not test whether the functionality works

2020-11-05 11:41 UTC, dteok commented on pygyver/etl/dw.py
> +        table_ref = dataset_ref.table(table_id)
i have considered that, but it is not that readable. I think it is better to be more explicit.

2020-11-05 11:44 UTC, KarimZaoui commented on pygyver/etl/dw.py
> +        table_ref = dataset_ref.table(table_id)
We need to make the code base consistent. We created the method `get_table_ref` to simplify the code and it is used in most methods needing to get the table ref.

2020-11-05 17:01 UTC, KarimZaoui commented on tests/test_dw.py
> +                                   {'BIGQUERY_START_DATE': '2020-01-01', 'BIGQUERY_END_DATE': '2020-01-05'})
@dannyteok I am not sure I understand the `setUp` here and how it is used in the test

2020-11-05 17:01 UTC, KarimZaoui commented on tests/test_dw.py
> +            self.db.delete_table(dataset_id='test', table_id='my_partition_table')
@dannyteok same as above, I dont understand the tear down here

2020-11-05 17:01 UTC, KarimZaoui commented on tests/test_pipeline.py
> +                        "description": "Happiness is wanting what you already have",
Why?

2020-11-05 18:05 UTC, KarimZaoui commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
@dannyteok I still don't understand why we are adding this row?

2020-11-05 18:05 UTC, KarimZaoui commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
Where is it being used?

2020-11-05 20:36 UTC, dteok commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
this is the pipeline test testing for when YAML passes the key 'description' to insert/edit the table's description. BigQuery Executor sees that the parameter is present and has value, it will then call on the bq exec to update the table with that description text.

2020-11-05 20:41 UTC, KarimZaoui commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
This does not test that the functionality works with pipeline executor. 

In this file, you only modified the yaml to have the new parameter description with value "some description test here", but you are not actually testing whether a table is being created with that description.

2020-11-06 00:38 UTC, dteok commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
that is done in test_dw.py

2020-11-06 01:21 UTC, dteok commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
fixed

2020-11-06 09:58 UTC, KarimZaoui commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
Its better now. 

FYI, the test files test_dw.py and test_pipeline.py are independent from each other and don't depend on each other. Your previous change to test_pipeline.py with no test associated to it was not sufficient.

2020-11-06 10:04 UTC, KarimZaoui commented
@dteok 

As mentioned by @charlielewis yesterday morning, could you add this capability to `load_google_sheet` and `create_partition_table` as well.

Let's skip changes to `initiate_table` and `create_gs_table` for now, even though it would be useful to have it there too.

2020-11-06 10:54 UTC, charlielewis commented
That makes a lot of sense -- not even sure you'd want descriptions on `create_gs_table()` -- unless it was some sort of automated metadata

2020-11-06 12:06 UTC, dteok commented on tests/test_pipeline.py
> +                        "description": "some descriptive text here",
I understand it better now, thank you!

2020-11-06 18:27 UTC, KarimZaoui commented on pygyver/etl/dw.py
> +                                          project_id=project_id, dataset_id=dataset_id)
@dannyteok we should not duplicate the logic that is already implemented in `create_table`, but add the new parameter `description` to the call of `create_table line 461.

2020-11-06 18:49 UTC, dteok commented on pygyver/etl/dw.py
> +                                          project_id=project_id, dataset_id=dataset_id)
I have tried that but won't work.
```
google.api_core.exceptions.BadRequest: 400 PATCH
Invalid table ID "my_partition_table$20200101". Table IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long.
```
I didn't understand it, but this was the work around. And this works

2020-11-06 23:00 UTC, dteok commented on pygyver/etl/dw.py
> +                                          project_id=project_id, dataset_id=dataset_id)
I have tried all ways and methods to include that as part of the create_table() call within create_partition_table(). Out of ideas, happy to pair if willing. Otherwise, the work around works for now -- MVP.

2020-11-09 11:15 UTC, KarimZaoui approved these changes

2020-11-09 11:16 UTC, KarimZaoui approved these changes

2020-11-09 11:21 UTC, merged