zendesk_downloader_updated
madedotcom/pygyver pull request #162
Opened 2021-05-26 16:02 UTC by tommy-watts

2021-05-26 16:18 UTC, dankruse1 requested changes

2021-05-26 16:18 UTC, dankruse1 commented on pygyver/etl/zendesk.py
>          Subsequent calls set the endpoint based on the returned `next_page` value from the previous call.
should probably amend this

2021-05-26 16:18 UTC, dankruse1 commented on pygyver/etl/zendesk.py
> +              self.endpoint = self.data.get("next_page", self.data.get("after_url"))
self.endpoint =next.endpoint

2021-05-27 13:36 UTC, jean-maldo submitted a review, later dismissed

2021-05-27 13:36 UTC, jean-maldo commented on pygyver/etl/zendesk.py
> +    def __init__(self, start_date=None, uri=None, sideload=None, per_page=500, limit=None, pagination=True, base_url="https://madecom.zendesk.com/"):
`pagination=True` should be removed right? Since it's not being used anymore.

2021-05-27 13:36 UTC, jean-maldo commented on pygyver/etl/zendesk.py
> +        # self.pagination = pagination
May as well delete rather than comment out

2021-05-27 13:36 UTC, jean-maldo commented on vars/build/default/default.env
> +IMAGE_REGISTRY=gcr.io/copper-actor-127213
Add new line

2021-05-27 13:36 UTC, jean-maldo commented on vars/build/default/default.env
> -PYTHONPATH=/code/src/
Reason for removing this?

2021-05-27 13:36 UTC, jean-maldo commented on vars/build/test/test.env
> -PROJECT_ROOT=/code/src/
Reason for removing this?

2021-05-27 13:36 UTC, jean-maldo commented on vars/env/default/default.env
> +PROJECT_ROOT=/code/src/
Add new line

2021-05-27 13:36 UTC, jean-maldo commented on vars/env/local/README.md
> -```
This file shouldn't be deleted

2021-05-27 13:36 UTC, jean-maldo commented on vars/env/test/test.env
> -GOODDATA_PROJECT="12345"
Should these be changed?

2021-06-21 15:37 UTC, dankruse1 requested changes

2021-06-21 15:37 UTC, dankruse1 commented on pygyver/etl/zendesk.py
>            pagination (bool, optional): Flag for if the endpoint has pagination.
delete

2021-06-21 15:37 UTC, dankruse1 commented on pygyver/etl/zendesk.py
>            pagination (bool, optional): Flag for if the endpoint has pagination.
and add limit

2021-06-21 15:37 UTC, dankruse1 commented on pygyver/etl/zendesk.py
> +      if self.limit:
add doc string

2021-06-21 15:44 UTC, dankruse1 requested changes

2021-06-21 15:44 UTC, dankruse1 commented on pygyver/etl/zendesk.py
> +        After each request update `self.endpoint` with the next_page endpoint provided in the response.
could maybe use a generic term here or say next_page/limit

2021-06-21 15:44 UTC, dankruse1 commented on pygyver/etl/zendesk.py
>            uri (str): API endpoint.
add start_time

2021-06-21 15:51 UTC, dankruse1 approved these changes

2021-06-21 16:25 UTC, merged